#!/usr/bin/env bash
#
# Copyright (C) 2022 Vaticle
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# TypeDB Studio global variables
JAVA_BIN=java
if [[ ! -z "$JAVA_HOME" ]]; then
    JAVA_BIN="$JAVA_HOME/bin/java"
fi
[[ $(readlink $0) ]] && path=$(readlink $0) || path=$0
STUDIO_HOME=$(cd "$(dirname "${path}")" && pwd -P)

# ================================================
# common helper functions
# ================================================
exit_if_java_not_found() {
    which "${JAVA_BIN}" > /dev/null
    exit_code=$?

    if [[ $exit_code -ne 0 ]]; then
        echo "Java is not installed on this machine. TypeDB Studio needs Java 11+ in order to run."
        exit 1
    fi
}

# =============================================
# main routine
# =============================================

exit_if_java_not_found

LIB_DIR="${STUDIO_HOME}/lib"
CLASSPATH="${LIB_DIR}/*"
MAIN_CLASS=com.vaticle.typedb.studio.view.Studio

# exec replaces current shell process with java so no commands after this one will ever get executed
exec $JAVA_BIN ${JAVAOPTS} -cp "${CLASSPATH}" ${MAIN_CLASS} "${@:1}"
