#!/usr/bin/env bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# TypeDB Studio global variables
JAVA_BIN=java
if [[ ! -z "$JAVA_HOME" ]]; then
    JAVA_BIN="$JAVA_HOME/bin/java"
fi
[[ $(readlink $0) ]] && path=$(readlink $0) || path=$0
STUDIO_HOME=$(cd "$(dirname "${path}")" && pwd -P)

# ================================================
# common helper functions
# ================================================
exit_if_java_not_found() {
    which "${JAVA_BIN}" > /dev/null
    exit_code=$?

    if [[ $exit_code -ne 0 ]]; then
        echo "Java is not installed on this machine. TypeDB Studio needs Java 11+ in order to run."
        exit 1
    fi
}

# =============================================
# main routine
# =============================================

exit_if_java_not_found

LIB_DIR="${STUDIO_HOME}/lib"
CLASSPATH="${LIB_DIR}/*"
MAIN_CLASS=com.typedb.studio.Studio

# exec replaces current shell process with java so no commands after this one will ever get executed
exec $JAVA_BIN ${JAVAOPTS} -cp "${CLASSPATH}" ${MAIN_CLASS} "${@:1}"
