[build]
publish = "dist/typedb-studio/browser"

[context.development]
command = "pnpm run build:dev"

[context.production]
command = "pnpm run build:prod"

[context.deploy-preview]
command = "pnpm run build:dev"

[[headers]]
for = "/*"

  [headers.values]
  X-Frame-Options = "DENY"
  Content-Security-Policy = "frame-ancestors 'none'"
  X-Content-Type-Options = "nosniff"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
