/*
 * Copyright (C) 2021 Vaticle
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

package com.vaticle.typedb.studio.view.common

object Label {

    const val ADDRESS = "Address"
    const val CA_CERTIFICATE = "CA Certificate"
    const val CANCEL = "Cancel"
    const val CASE_SENSITIVE = "Case Sensitive"
    const val CLOSE = "Close"
    const val CLOSING_TYPEDB_STUDIO = "Closing TypeDB Studio"
    const val CMD = "cmd"
    const val COMMIT = "Commit"
    const val COMMIT_TRANSACTION = "Commit Transaction"
    const val CONFIRM = "Confirm"
    const val CONFIRM_DIRECTORY_DELETION = "Confirm Directory Deletion"
    const val CONFIRM_FILE_DELETION = "Confirm File Deletion"
    const val CONNECT = "Connect"
    const val CONNECTING = "Connecting..."
    const val CONNECT_TO_TYPEDB = "Connect to TypeDB"
    const val COPY = "Copy"
    const val CREATE = "Create"
    const val CREATE_DIRECTORY = "Create Directory"
    const val CREATE_FILE = "Create file"
    const val CTRL = "ctrl"
    const val CUT = "Cut"
    const val DATA_SESSION = "Data Session"
    const val DELETE = "Delete"
    const val DIRECTORY = "Directory"
    const val DIRECTORY_NAME = "Directory Name"
    const val DISCONNECT = "Disconnect"
    const val DISMISS_ALL = "Dismiss All"
    const val ENABLE_INFERENCE = "Enable Inference"
    const val ENABLE_INFERENCE_EXPLANATION = "Enable Inference Explanation"
    const val ENABLE_SNAPSHOT = "Enable Snapshot"
    const val ENABLE_TLS = "Enable TLS"
    const val EXACT_WORD = "Exact Word"
    const val EXPAND_COLLAPSE = "Expand/Collapse"
    const val EXPLAIN = "Explain"
    const val FILE_NAME = "File Name"
    const val FIND = "Find"
    const val FOUND = "Found"
    const val INFER = "Infer"
    const val INTERACTIVE_MODE = "Interactive Mode"
    const val LEARN_MORE = "Learn More"
    const val MOVE = "Move"
    const val MOVE_DIRECTORY = "Move Directory"
    const val NEXT_OCCURRENCE = "Next Occurrence"
    const val NONE = "None"
    const val OPEN = "Open"
    const val OPEN_PROJECT = "Open Project"
    const val OPEN_PROJECT_DIRECTORY = "Open Project Directory"
    const val OPTIONAL = "Optional"
    const val PASSWORD = "Password"
    const val PASTE = "Paste"
    const val PATH_TO_CA_CERTIFICATE = "/path/to/ca/certificate"
    const val PATH_OF_DIRECTORY = "/path/of/directory"
    const val PREVIOUS_OCCURRENCE = "Previous Occurrence"
    const val PROJECT = "Project"
    const val PROJECT_BROWSER = "Project Browser"
    const val QUERY = "Query"
    const val READ_MORE = "Read More"
    const val READ_ONLY = "Read Only"
    const val READ_TRANSACTION = "Read Transaction"
    const val REGULAR_EXPRESSION = "Regular Expression"
    const val RENAME = "Rename"
    const val RENAME_DIRECTORY = "Rename Directory"
    const val RENAME_FILE = "Rename File"
    const val REOPEN = "Reopen"
    const val CLOSE_TRANSACTION = "Reopen Transaction"
    const val REPLACE = "Replace"
    const val REPLACE_ALL = "Replace All"
    const val REPLACE_ALL_OCCURRENCES = "Replace All Occurrences"
    const val REPLACE_NEXT_OCCURRENCE = "Replace Next Occurrence"
    const val ROLES = "Roles"
    const val ROLLBACK = "Rollback"
    const val ROLLBACK_TRANSACTION = "Rollback Transaction"
    const val RULES = "Rules"
    const val RUN_QUERY = "Run Query"
    const val RUN_SCRIPT = "Run Script"
    const val SAVE = "Save"
    const val SAVE_CURRENT_FILE = "Save Current File"
    const val SAVE_FILE = "Save File"
    const val SAVE_OR_DELETE = "Save or Delete"
    const val SCHEMA_SESSION = "Schema Session"
    const val SCRIPT_MODE = "Script Mode"
    const val SELECT_DATABASE = "Select Database"
    const val SERVER = "Server"
    const val SESSION_TYPE = "Session Type"
    const val SNAPSHOT = "Snapshot"
    const val STATUS = "Status"
    const val STOP = "Stop"
    const val TITLE = "Title"
    const val TRACE = "Trace"
    const val TRANSACTION_STATUS = "Transaction Status"
    const val TRANSACTION_TYPE = "Transaction Type"
    const val TYPEDB_STUDIO = "TypeDB Studio"
    const val TYPEDB_STUDIO_APPLICATION_ERROR = "TypeDB Studio Application Error"
    const val TYPES = "Types"
    const val UNTITLED = "Untitled"
    const val USERNAME = "Username"
    const val USERS = "Users"
    const val WRITE_TRANSACTION = "Write Transaction"
}
