package(default_visibility = ["//:__pkg__"])

filegroup(
    name = "light",
    srcs = ["TitilliumWeb-Light.ttf"]
)

filegroup(
    name = "regular",
    srcs = ["TitilliumWeb-Regular.ttf"]
)

filegroup(
    name = "semi-bold",
    srcs = ["TitilliumWeb-SemiBold.ttf"]
)
