package(default_visibility = ["//:__pkg__"])

exports_files(["blueprint-codepoints-reference.json"])

filegroup(
    name = "blueprint-icons-16",
    srcs = ["blueprint-icons-16.ttf"],
)

filegroup(
    name = "blueprint-icons-20",
    srcs = ["blueprint-icons-20.ttf"],
)
