package(default_visibility = ["//:__pkg__"])

exports_files(["blueprint-codepoints-reference.json"])

filegroup(
    name = "icons",
    srcs = [
        "database.png",
        "database.svg",
        "blueprint-icons-16.ttf",
        "blueprint-icons-20.ttf",
    ],
)
