package(default_visibility = ["//:__pkg__"])

filegroup(
    name = "entitlements-mac-plist",
    srcs = ["entitlements.mac.plist"],
)

filegroup(
    name = "logback-xml",
    srcs = ["logback.xml"]
)
