package(default_visibility = ["//:__pkg__"])

filegroup(
    name = "entitlements-mac-plist",
    srcs = ["entitlements.mac.plist"],
)

filegroup(
    name = "logback-test-xml",
    srcs = ["logback-test.xml"],
)

filegroup(
    name = "logback-xml",
    srcs = ["logback.xml"],
)
