package(default_visibility = ["//:__pkg__"])

filegroup(
    name = "titillium-web",
    srcs = [
        "titilliumweb/TitilliumWeb-Light.ttf",
        "titilliumweb/TitilliumWeb-Regular.ttf",
        "titilliumweb/TitilliumWeb-SemiBold.ttf",
    ]
)

filegroup(
    name = "ubuntu-mono",
    srcs = [
        "ubuntumono/UbuntuMono-Bold.ttf",
        "ubuntumono/UbuntuMono-Regular.ttf",
    ]
)
