package(default_visibility = ["//:__pkg__"])

filegroup(
    name = "fonts",
    srcs = [
        "TitilliumWeb/TitilliumWeb-Light.ttf",
        "TitilliumWeb/TitilliumWeb-Regular.ttf",
        "TitilliumWeb/TitilliumWeb-SemiBold.ttf",

        "UbuntuMono/UbuntuMono-Bold.ttf",
        "UbuntuMono/UbuntuMono-Regular.ttf",
    ]
)
