package(default_visibility = ["//:__pkg__"])

filegroup(
    name = "vaticle-bot-linux",
    srcs = ["256x256.png"],
)

filegroup(
    name = "vaticle-bot-mac",
    srcs = ["vaticle-bot.icns"],
)

filegroup(
    name = "vaticle-bot-windows",
    srcs = ["vaticle-bot.ico"],
)
